<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Proto.Cluster.Identity.PostgreSql\Proto.Cluster.Identity.PostgreSql.csproj" />
        <ProjectReference Include="..\..\src\Proto.Cluster.SeedNode.PostgreSql\Proto.Cluster.SeedNode.PostgreSql.csproj" />
        <ProjectReference Include="..\Proto.Cluster.Identity.Tests\Proto.Cluster.Identity.Tests.csproj" />
        <ProjectReference Include="..\Proto.Cluster.Tests\Proto.Cluster.Tests.csproj" />
        <ProjectReference Include="..\Proto.TestFixtures\Proto.TestFixtures.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Neovolve.Logging.Xunit" />
    </ItemGroup>
    <ItemGroup>
        <None Update="*.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
    </ItemGroup>
</Project>
