<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <PropertyGroup>
        <NoWarn>8981</NoWarn>
        <RootNamespace>Proto</RootNamespace>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <LangVersion>10</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos.proto" GrpcServices="Server" />
    </ItemGroup>
</Project>
